//! Renders a ready-to-paste Herdr keybinding snippet (TOML).

use crate::detect::{direction, DIRECTION_NAMES};

/// Canonical command name used in the snippet's header comments.
pub const HELPER_NAME: &str = "herdr-vim-navigator";

fn block(key: &str, command: &str, description: &str) -> String {
    format!(
        "[[keys.command]]\n\
         key = \"{key}\"\n\
         type = \"shell\"\n\
         command = \"{command}\"\n\
         description = \"{description}\"\n"
    )
}

/// Return a Herdr keybinding snippet to paste into a config.
///
/// `helper` is the command name used in the generated `command = "..."` lines.
/// `arrows` also emits `ctrl+arrow` bindings; `splits` appends commented
/// split-binding examples.
pub fn render(helper: &str, arrows: bool, splits: bool) -> String {
    let mut generated = format!("# Generated by: {HELPER_NAME} config");
    if arrows {
        generated.push_str(" --arrows");
    }
    if splits {
        generated.push_str(" --splits");
    }

    let mut header = String::new();
    header.push_str(&format!(
        "# {HELPER_NAME} — add these to your Herdr config (keybindings).\n"
    ));
    header.push_str(&generated);
    header.push('\n');

    let mut blocks: Vec<String> = Vec::new();
    for name in DIRECTION_NAMES {
        let d = direction(name).expect("known direction");
        blocks.push(block(
            d.ctrl_key,
            &format!("{helper} dispatch {}", d.name),
            &format!("vim-aware pane {}", d.name),
        ));
    }

    if arrows {
        for name in DIRECTION_NAMES {
            let d = direction(name).expect("known direction");
            blocks.push(block(
                d.arrow_key,
                &format!("{helper} dispatch {}", d.name),
                &format!("vim-aware pane {}", d.name),
            ));
        }
    }

    let mut snippet = header + &blocks.join("\n");

    if splits {
        snippet.push_str(&format!(
            "\n# Optional split bindings — choose keys that don't clash with your setup:\n\
             # [[keys.command]]\n\
             # key = \"<your-key>\"\n\
             # type = \"shell\"\n\
             # command = \"{helper} split right\"\n\
             # description = \"vim-aware split right\"\n\
             #\n\
             # [[keys.command]]\n\
             # key = \"<your-key>\"\n\
             # type = \"shell\"\n\
             # command = \"{helper} split down\"\n\
             # description = \"vim-aware split down\"\n"
        ));
    }

    snippet
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_snippet_emits_all_dispatch_directions() {
        let snippet = render(HELPER_NAME, false, false);
        for (key, name) in [
            ("ctrl+h", "left"),
            ("ctrl+j", "down"),
            ("ctrl+k", "up"),
            ("ctrl+l", "right"),
        ] {
            assert!(snippet.contains(&format!("key = \"{key}\"")));
            assert!(snippet.contains(&format!("herdr-vim-navigator dispatch {name}")));
        }
        // Arrow bindings are opt-in.
        assert!(!snippet.contains("ctrl+left"));
    }

    #[test]
    fn arrows_flag_adds_arrow_bindings() {
        let snippet = render(HELPER_NAME, true, false);
        for key in ["ctrl+left", "ctrl+down", "ctrl+up", "ctrl+right"] {
            assert!(snippet.contains(&format!("key = \"{key}\"")));
        }
    }

    #[test]
    fn custom_helper_name_is_used_in_commands() {
        let snippet = render("/opt/bin/hvn", false, false);
        assert!(snippet.contains("/opt/bin/hvn dispatch left"));
    }

    #[test]
    fn splits_flag_adds_commented_examples() {
        let snippet = render(HELPER_NAME, false, true);
        assert!(snippet.contains("# command = \"herdr-vim-navigator split right\""));
        assert!(snippet.contains("# command = \"herdr-vim-navigator split down\""));
    }
}
