//! Renders a ready-to-paste Herdr keybinding snippet (TOML).

use crate::detect::{DIRECTION_NAMES, direction};

/// Canonical command name used in the snippet's header comments.
pub const HELPER_NAME: &str = "vim-herdr-navigator";

fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn shell_quote(value: &str) -> String {
    let is_safe = !value.is_empty()
        && value.chars().all(|ch| {
            ch.is_ascii_alphanumeric() || matches!(ch, '/' | '.' | '_' | '-' | ':' | '@' | '+')
        });

    if is_safe {
        value.to_string()
    } else {
        format!("'{}'", value.replace('\'', "'\\''"))
    }
}

fn block(key: &str, command: &str, description: &str) -> String {
    format!(
        "[[keys.command]]\n\
         key = \"{}\"\n\
         type = \"shell\"\n\
         command = \"{}\"\n\
         description = \"{}\"\n",
        toml_string(key),
        toml_string(command),
        toml_string(description)
    )
}

/// Return a Herdr keybinding snippet to paste into a config.
///
/// `helper` is the command name used in the generated `command = "..."` lines.
pub fn render(helper: &str) -> String {
    let helper = shell_quote(helper);

    let mut header = String::new();
    header.push_str(&format!(
        "# {HELPER_NAME}: add these to your Herdr config (keybindings).\n"
    ));
    header.push_str(&format!("# Generated by: {HELPER_NAME} config\n"));

    let mut blocks: Vec<String> = Vec::new();
    for name in DIRECTION_NAMES {
        let d = direction(name).expect("known direction");
        blocks.push(block(
            d.ctrl_key,
            &format!("{helper} dispatch {}", d.name),
            &format!("vim-aware pane {}", d.name),
        ));
    }

    header + &blocks.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_snippet_emits_all_dispatch_directions() {
        let snippet = render(HELPER_NAME);
        for (key, name) in [
            ("ctrl+h", "left"),
            ("ctrl+j", "down"),
            ("ctrl+k", "up"),
            ("ctrl+l", "right"),
        ] {
            assert!(snippet.contains(&format!("key = \"{key}\"")));
            assert!(snippet.contains(&format!("vim-herdr-navigator dispatch {name}")));
        }
    }

    #[test]
    fn custom_helper_name_is_used_in_commands() {
        let snippet = render("/opt/bin/hvn");
        assert!(snippet.contains("/opt/bin/hvn dispatch left"));
    }

    #[test]
    fn helper_path_is_shell_quoted_and_toml_escaped() {
        let snippet = render("/Applications/My Tools/hv'n");
        assert!(
            snippet.contains("command = \"'/Applications/My Tools/hv'\\\\''n' dispatch left\"")
        );
    }
}
